spring.application.name=SupplyFlow

spring.datasource.url=jdbc:mysql://localhost:3306/SupplyFlow
spring.datasource.username=root
spring.datasource.password=Zakaria@741
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver